//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Core/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""efe7c45a-4270-4c68-b821-a01589efef13"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d781a728-1e04-438d-ad9e-89923880f12d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""d4f75a51-cda7-432b-8af2-feba6b21ca32"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""33fbc281-7484-4b92-981d-f158fdbac007"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MapBtn"",
                    ""type"": ""Button"",
                    ""id"": ""ac3fd735-cb71-413f-b528-5c08288011d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractionBtn"",
                    ""type"": ""Button"",
                    ""id"": ""4f0681a7-acf9-4dc0-b44d-6624c1bba917"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftBtn"",
                    ""type"": ""Button"",
                    ""id"": ""dc7a215b-90a7-4539-9faf-e617e7eb6dde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightBtn"",
                    ""type"": ""Button"",
                    ""id"": ""22472e24-5cfb-48b3-88e9-6580607ef6da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseBtn"",
                    ""type"": ""Button"",
                    ""id"": ""8185a924-abe2-4517-9352-5447ab7b14a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraAxesX"",
                    ""type"": ""Value"",
                    ""id"": ""5dda93b6-8271-4c39-b672-17aec4c71e57"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraAxesY"",
                    ""type"": ""Value"",
                    ""id"": ""166f9957-4ce8-47f4-8300-477401600171"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""3408fd6e-1b48-487a-b1c2-c122f73a6f54"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""c5063f89-4a29-4572-8c01-bd9af1e17f3e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""9f5e5277-23d5-4ebf-9f5a-93d582827c54"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TakeBtn"",
                    ""type"": ""Button"",
                    ""id"": ""f5dd5756-6111-416b-aeed-fa7129d24fde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseBtn"",
                    ""type"": ""Button"",
                    ""id"": ""ef569c8f-36fe-4b8c-bef3-cef4d438fe86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpgradeBtn"",
                    ""type"": ""Button"",
                    ""id"": ""a405e918-fb47-4df5-b9cb-d3eb9774ec06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""RightStick"",
                    ""id"": ""ae3a82fd-1f30-47da-bced-d6db88b46032"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d38cd3bc-40de-477c-8478-5df8daa753e2"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""80f1ea18-217b-4b19-bdf8-e793ae58ec38"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b303db1d-9162-4719-8673-6782db76d125"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cb7693a8-0cb5-4ac3-9de3-9b2b5be0243a"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""aea32ee5-b64d-4cc8-81c4-d09f60ebedd3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6c967541-7e1b-47c9-accd-81214a2a0da1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9e19c5ac-4001-40dc-ac86-3582772e9223"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f101d9f6-d314-4b40-8615-3e5b8d88765e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""15faa0a4-c7d7-4b1e-8d71-e00c232aef1c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow"",
                    ""id"": ""ad5b17f0-6e68-4fd9-85c9-86845b3e511c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""325f6587-5f77-4894-b280-fc8a4a4a2140"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c9fca5ed-3a54-400c-a720-a5e00437dd97"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f22ddf1e-8932-4caf-a820-2085600cd46b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""39ec6cc2-28f3-4307-a588-246378a76288"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4f4281cc-3ca7-4f29-aa28-5d0869a72962"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54ea07c5-45fb-4963-be05-f74e8d7e6a70"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a68dbbc6-76c0-4a7e-9a6e-9875b67e5543"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1714e1f-7a25-4f27-a92b-53b33214abb9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""273f3d6c-91cd-4caf-b00c-9ec21adad9b5"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""MapBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14911298-e1da-4a1b-811e-12dba4d75357"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MapBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f8a67a9-274a-4e79-b702-360a470185dd"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""InteractionBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e6e0389-14b3-4d15-bdd8-4ab5e92aff02"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""InteractionBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43e97d03-a84d-4be6-a40e-94d3089a1026"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""LeftBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0aa70642-bdbe-40ab-ae10-16979e6e0d22"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LeftBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b646fa5-6b7a-4c1a-8e7a-649a958eb30a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""RightBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd3627f6-1513-44f8-aa6c-4dcda88f4b25"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1aa2f303-95b4-408f-bee8-cdf1ee4b7764"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""PauseBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a450ae78-2f8e-4a96-87ae-c6b30cb5638d"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PauseBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d53711b-8475-4157-854a-75c4256ba8dc"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""CameraAxesX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddc36845-fc3f-493c-89d3-bb0f237b083e"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraAxesX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abcecbfd-00f6-4712-a433-263f5e303778"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""CameraAxesY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d50f1ff-9abb-4c69-aa73-eff5ca0bae7d"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraAxesY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f704b0c3-0e18-4e70-a96e-d9a4cff1faa2"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bba7d30-7503-4fb9-a42e-3b27f346b41f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dafc4e13-c8bf-4d55-b823-4d6246881105"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96580fa3-874b-4bc1-ba1a-93af47e01b32"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""603c5234-ce0a-4eba-9f2f-c7493da1bbd5"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b721ac8-2c62-4ed4-8566-97de25867f52"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08463fc5-d7f8-4302-ac16-3669f3c9c59e"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""TakeBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d53e6f76-6935-4946-bb92-d4c6ed65ba6a"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""TakeBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bd53a6a-aaed-4a01-ad75-5b920efba5ac"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""CloseBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d4d9082-e634-4d71-ae5c-4dffa015234f"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpgradeBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""MouseKeyboard"",
            ""bindingGroup"": ""MouseKeyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Reload = m_Player.FindAction("Reload", throwIfNotFound: true);
        m_Player_Shoot = m_Player.FindAction("Shoot", throwIfNotFound: true);
        m_Player_MapBtn = m_Player.FindAction("MapBtn", throwIfNotFound: true);
        m_Player_InteractionBtn = m_Player.FindAction("InteractionBtn", throwIfNotFound: true);
        m_Player_LeftBtn = m_Player.FindAction("LeftBtn", throwIfNotFound: true);
        m_Player_RightBtn = m_Player.FindAction("RightBtn", throwIfNotFound: true);
        m_Player_PauseBtn = m_Player.FindAction("PauseBtn", throwIfNotFound: true);
        m_Player_CameraAxesX = m_Player.FindAction("CameraAxesX", throwIfNotFound: true);
        m_Player_CameraAxesY = m_Player.FindAction("CameraAxesY", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_TakeBtn = m_Player.FindAction("TakeBtn", throwIfNotFound: true);
        m_Player_CloseBtn = m_Player.FindAction("CloseBtn", throwIfNotFound: true);
        m_Player_UpgradeBtn = m_Player.FindAction("UpgradeBtn", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Reload;
    private readonly InputAction m_Player_Shoot;
    private readonly InputAction m_Player_MapBtn;
    private readonly InputAction m_Player_InteractionBtn;
    private readonly InputAction m_Player_LeftBtn;
    private readonly InputAction m_Player_RightBtn;
    private readonly InputAction m_Player_PauseBtn;
    private readonly InputAction m_Player_CameraAxesX;
    private readonly InputAction m_Player_CameraAxesY;
    private readonly InputAction m_Player_Sprint;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_TakeBtn;
    private readonly InputAction m_Player_CloseBtn;
    private readonly InputAction m_Player_UpgradeBtn;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Reload => m_Wrapper.m_Player_Reload;
        public InputAction @Shoot => m_Wrapper.m_Player_Shoot;
        public InputAction @MapBtn => m_Wrapper.m_Player_MapBtn;
        public InputAction @InteractionBtn => m_Wrapper.m_Player_InteractionBtn;
        public InputAction @LeftBtn => m_Wrapper.m_Player_LeftBtn;
        public InputAction @RightBtn => m_Wrapper.m_Player_RightBtn;
        public InputAction @PauseBtn => m_Wrapper.m_Player_PauseBtn;
        public InputAction @CameraAxesX => m_Wrapper.m_Player_CameraAxesX;
        public InputAction @CameraAxesY => m_Wrapper.m_Player_CameraAxesY;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @TakeBtn => m_Wrapper.m_Player_TakeBtn;
        public InputAction @CloseBtn => m_Wrapper.m_Player_CloseBtn;
        public InputAction @UpgradeBtn => m_Wrapper.m_Player_UpgradeBtn;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Reload.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReload;
                @Shoot.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @MapBtn.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMapBtn;
                @MapBtn.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMapBtn;
                @MapBtn.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMapBtn;
                @InteractionBtn.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractionBtn;
                @InteractionBtn.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractionBtn;
                @InteractionBtn.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractionBtn;
                @LeftBtn.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftBtn;
                @LeftBtn.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftBtn;
                @LeftBtn.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftBtn;
                @RightBtn.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightBtn;
                @RightBtn.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightBtn;
                @RightBtn.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightBtn;
                @PauseBtn.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseBtn;
                @PauseBtn.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseBtn;
                @PauseBtn.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseBtn;
                @CameraAxesX.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCameraAxesX;
                @CameraAxesX.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCameraAxesX;
                @CameraAxesX.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCameraAxesX;
                @CameraAxesY.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCameraAxesY;
                @CameraAxesY.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCameraAxesY;
                @CameraAxesY.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCameraAxesY;
                @Sprint.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @TakeBtn.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTakeBtn;
                @TakeBtn.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTakeBtn;
                @TakeBtn.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTakeBtn;
                @CloseBtn.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCloseBtn;
                @CloseBtn.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCloseBtn;
                @CloseBtn.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCloseBtn;
                @UpgradeBtn.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUpgradeBtn;
                @UpgradeBtn.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUpgradeBtn;
                @UpgradeBtn.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUpgradeBtn;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @MapBtn.started += instance.OnMapBtn;
                @MapBtn.performed += instance.OnMapBtn;
                @MapBtn.canceled += instance.OnMapBtn;
                @InteractionBtn.started += instance.OnInteractionBtn;
                @InteractionBtn.performed += instance.OnInteractionBtn;
                @InteractionBtn.canceled += instance.OnInteractionBtn;
                @LeftBtn.started += instance.OnLeftBtn;
                @LeftBtn.performed += instance.OnLeftBtn;
                @LeftBtn.canceled += instance.OnLeftBtn;
                @RightBtn.started += instance.OnRightBtn;
                @RightBtn.performed += instance.OnRightBtn;
                @RightBtn.canceled += instance.OnRightBtn;
                @PauseBtn.started += instance.OnPauseBtn;
                @PauseBtn.performed += instance.OnPauseBtn;
                @PauseBtn.canceled += instance.OnPauseBtn;
                @CameraAxesX.started += instance.OnCameraAxesX;
                @CameraAxesX.performed += instance.OnCameraAxesX;
                @CameraAxesX.canceled += instance.OnCameraAxesX;
                @CameraAxesY.started += instance.OnCameraAxesY;
                @CameraAxesY.performed += instance.OnCameraAxesY;
                @CameraAxesY.canceled += instance.OnCameraAxesY;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @TakeBtn.started += instance.OnTakeBtn;
                @TakeBtn.performed += instance.OnTakeBtn;
                @TakeBtn.canceled += instance.OnTakeBtn;
                @CloseBtn.started += instance.OnCloseBtn;
                @CloseBtn.performed += instance.OnCloseBtn;
                @CloseBtn.canceled += instance.OnCloseBtn;
                @UpgradeBtn.started += instance.OnUpgradeBtn;
                @UpgradeBtn.performed += instance.OnUpgradeBtn;
                @UpgradeBtn.canceled += instance.OnUpgradeBtn;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_MouseKeyboardSchemeIndex = -1;
    public InputControlScheme MouseKeyboardScheme
    {
        get
        {
            if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("MouseKeyboard");
            return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnMapBtn(InputAction.CallbackContext context);
        void OnInteractionBtn(InputAction.CallbackContext context);
        void OnLeftBtn(InputAction.CallbackContext context);
        void OnRightBtn(InputAction.CallbackContext context);
        void OnPauseBtn(InputAction.CallbackContext context);
        void OnCameraAxesX(InputAction.CallbackContext context);
        void OnCameraAxesY(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnTakeBtn(InputAction.CallbackContext context);
        void OnCloseBtn(InputAction.CallbackContext context);
        void OnUpgradeBtn(InputAction.CallbackContext context);
    }
}
